import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title='Neon City', page_icon='🌃', layout='wide')

components.html(r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#02030a}canvas{display:block}#intro{position:fixed;inset:0;z-index:20;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(circle,#18204b,#070914 45%,#010208);color:#fff;font:14px Arial;text-align:center;transition:opacity 1.2s}#intro h1{margin:0;font-size:clamp(50px,9vw,120px);font-weight:200;letter-spacing:18px;text-shadow:0 0 12px #00eaff,0 0 35px #00eaff,0 0 80px #ff0088}#intro p{letter-spacing:6px;color:#b9c4df}#enter{margin-top:40px;padding:16px 45px;background:#00eaff08;border:1px solid #00eaff;color:#00eaff;letter-spacing:5px;cursor:pointer}#enter:hover{background:#00eaff;color:#02030a;box-shadow:0 0 25px #00eaff}#hud{position:fixed;left:20px;top:18px;z-index:10;color:#dbe6ff99;font:11px Arial;letter-spacing:3px;opacity:0;transition:opacity 1.5s;pointer-events:none}#hint{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:10;color:#fff8;font:11px Arial;letter-spacing:2px;opacity:0;transition:opacity 1.5s;pointer-events:none}
</style></head><body>
<div id="intro"><h1>NEON CITY</h1><p>A LIVING CITY AFTER MIDNIGHT</p><button id="enter">ENTER</button></div><div id="hud">NEON DISTRICT · 02:17 AM · RAIN 78%</div><div id="hint">W A S D · ARROWS TO WALK · HOLD MOUSE TO LOOK</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script><script>
let S,C,R,T,yaw=0,pitch=0,drag=false,lx=0,ly=0,rain,cars=[],signs=[],K={};
const rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[(Math.random()*a.length)|0];
function glow(p,c,i=3,d=40){let l=new THREE.PointLight(c,i,d);l.position.copy(p);S.add(l)}
function tex(t,c){let x=document.createElement('canvas');x.width=512;x.height=160;let q=x.getContext('2d');q.fillStyle='#050713';q.fillRect(0,0,512,160);q.font='bold 62px Arial';q.textAlign='center';q.textBaseline='middle';q.shadowBlur=30;q.shadowColor=c;q.fillStyle=c;q.fillText(t,256,82);return new THREE.CanvasTexture(x)}
function world(){
 S=new THREE.Scene();S.background=new THREE.Color(0x030510);S.fog=new THREE.FogExp2(0x070a18,.0075);
 C=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,1800);C.position.set(0,2.15,36);
 R=new THREE.WebGLRenderer({antialias:true});R.setPixelRatio(Math.min(devicePixelRatio,2));R.setSize(innerWidth,innerHeight);R.outputEncoding=THREE.sRGBEncoding;R.toneMapping=THREE.ACESFilmicToneMapping;R.toneMappingExposure=1.15;R.shadowMap.enabled=true;R.shadowMap.type=THREE.PCFSoftShadowMap;document.body.appendChild(R.domElement);T=new THREE.Clock();
 let dome=new THREE.Mesh(new THREE.SphereGeometry(900,32,16),new THREE.MeshBasicMaterial({color:0x02040e,side:THREE.BackSide}));S.add(dome);let moon=new THREE.Mesh(new THREE.SphereGeometry(13,24,24),new THREE.MeshBasicMaterial({color:0x9eb7ff}));moon.position.set(-180,150,-430);S.add(moon);
 S.add(new THREE.HemisphereLight(0x344b85,0x020207,1.25));let sun=new THREE.DirectionalLight(0x6688ff,.65);sun.position.set(-100,180,80);S.add(sun);glow(new THREE.Vector3(-42,18,-80),0x00d9ff,14,160);glow(new THREE.Vector3(42,22,-150),0xff0088,16,170);
 road();city();details();neon();traffic();makeRain();steam();controls();animate();
}
function road(){let m=new THREE.MeshStandardMaterial({color:0x07090f,roughness:.1,metalness:.9}),r=new THREE.Mesh(new THREE.PlaneGeometry(54,1700),m);r.rotation.x=-Math.PI/2;S.add(r);for(let i=0;i<28;i++){let p=new THREE.Mesh(new THREE.PlaneGeometry(rand(3,14),rand(5,28)),new THREE.MeshStandardMaterial({color:0x10192a,roughness:.03,metalness:.95,transparent:true,opacity:rand(.25,.65)}));p.rotation.x=-Math.PI/2;p.position.set(rand(-21,21),.01,rand(-800,800));S.add(p)}for(let x of [-33,33]){let s=new THREE.Mesh(new THREE.BoxGeometry(12,1.1,1700),new THREE.MeshStandardMaterial({color:0x11131c,roughness:.5}));s.position.set(x,.55,0);S.add(s)}for(let z=-800;z<800;z+=18)for(let x of [-13,13]){let q=new THREE.Mesh(new THREE.PlaneGeometry(.18,7),new THREE.MeshBasicMaterial({color:0x7fa5c8,transparent:true,opacity:.4}));q.rotation.x=-Math.PI/2;q.position.set(x,.012,z);S.add(q)}}
function city(){for(let z=-820;z<820;z+=30){building(-1,z);building(1,z)}for(let i=0;i<70;i++){let b=building(Math.random()<.5?-1:1,rand(-800,100));b.position.x*=rand(1.6,2.5)}}
function building(side,z){let w=rand(17,29),d=rand(24,42),h=rand(38,170),g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:pick([0x0a0d18,0x101322,0x141629,0x0b101c,0x17172a]),roughness:.45,metalness:.5}),b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);b.position.y=h/2;b.castShadow=true;g.add(b);for(let y=7;y<h;y+=7)for(let x=-w/2+2;x<w/2-1;x+=4)if(Math.random()<.7){let win=new THREE.Mesh(new THREE.PlaneGeometry(2.2,1.05),new THREE.MeshBasicMaterial({color:pick([0x7deaff,0xff5ebc,0xffc56b,0x8e82ff]),transparent:true,opacity:rand(.3,.8)}));win.position.set(side>0?-w/2-.04:w/2+.04,y,x);win.rotation.y=side>0?-Math.PI/2:Math.PI/2;g.add(win)}g.position.set(side*rand(38,49),0,z);S.add(g);return g}
function details(){for(let z=-780;z<780;z+=26){lamp(-21,z);lamp(21,z)}for(let z=-720;z<720;z+=110){let b=new THREE.Mesh(new THREE.BoxGeometry(105,2.4,5),new THREE.MeshStandardMaterial({color:0x161c2a,metalness:.9,roughness:.24}));b.position.set(0,rand(34,58),z);S.add(b);let n=new THREE.Mesh(new THREE.BoxGeometry(98,.22,.25),new THREE.MeshBasicMaterial({color:Math.random()<.5?0x00eaff:0xff0088}));n.position.set(0,b.position.y-1.2,z);S.add(n)}}
function lamp(x,z){let p=new THREE.Mesh(new THREE.CylinderGeometry(.1,.16,8.5),new THREE.MeshStandardMaterial({color:0x303746,metalness:.9}));p.position.set(x,4.25,z);S.add(p);let c=Math.random()<.5?0x00eaff:0xff1595;let b=new THREE.Mesh(new THREE.SphereGeometry(.35,10,10),new THREE.MeshBasicMaterial({color:c}));b.position.set(x,8.7,z);S.add(b);glow(new THREE.Vector3(x,8.5,z),c,2.2,28)}
function neon(){let words=['NOVA','NEXUS','VOID','LUNA','SYNTH','ZEN','ARIA','24H','HOTEL','CLUB','KAZE','METRO','ORBIT','ECHO','NIGHT'];for(let i=0;i<90;i++){let side=Math.random()<.5?-1:1,c=Math.random()<.5?'#00eaff':'#ff1595',s=new THREE.Mesh(new THREE.PlaneGeometry(rand(8,15),rand(2.5,4.5)),new THREE.MeshBasicMaterial({map:tex(pick(words),c),transparent:true}));s.position.set(side*rand(29,37),rand(7,110),rand(-800,800));s.rotation.y=side>0?-Math.PI/2:Math.PI/2;S.add(s);signs.push(s)}}
function traffic(){for(let i=0;i<28;i++){let g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(4.4,1.25,8),new THREE.MeshStandardMaterial({color:pick([0x0a0d14,0x171b27,0x21101e]),metalness:.9,roughness:.17}));b.position.y=1;g.add(b);let glass=new THREE.Mesh(new THREE.BoxGeometry(3.4,.7,2.4),new THREE.MeshStandardMaterial({color:0x152238,metalness:.7,roughness:.1}));glass.position.set(0,1.75,-.2);g.add(glass);let rear=new THREE.Mesh(new THREE.BoxGeometry(3.7,.16,.18),new THREE.MeshBasicMaterial({color:0xff003f}));rear.position.set(0,1.45,4.05);g.add(rear);let front=rear.clone();front.material=new THREE.MeshBasicMaterial({color:0xd9f7ff});front.position.z=-4.05;g.add(front);let lane=Math.random()<.5?-9:9;g.position.set(lane,0,rand(-800,800));g.userData.speed=rand(18,36)*(lane<0?1:-1);g.rotation.y=lane<0?0:Math.PI;S.add(g);cars.push(g)}}
function makeRain(){let n=8500,g=new THREE.BufferGeometry(),p=new Float32Array(n*3);for(let i=0;i<n;i++){p[i*3]=rand(-85,85);p[i*3+1]=rand(0,110);p[i*3+2]=rand(-500,250)}g.setAttribute('position',new THREE.BufferAttribute(p,3));rain=new THREE.Points(g,new THREE.PointsMaterial({color:0xaedfff,size:.13,transparent:true,opacity:.72}));S.add(rain)}
function steam(){for(let i=0;i<28;i++){let s=new THREE.Mesh(new THREE.CylinderGeometry(1.3,2.3,10,12,1,true),new THREE.MeshBasicMaterial({color:0x8d98ad,transparent:true,opacity:.045,side:THREE.DoubleSide}));s.position.set(Math.random()<.5?-27:27,5,rand(-800,800));S.add(s)}}
function controls(){addEventListener('keydown',e=>K[e.key.toLowerCase()]=true);addEventListener('keyup',e=>K[e.key.toLowerCase()]=false);addEventListener('mousedown',e=>{drag=true;lx=e.clientX;ly=e.clientY});addEventListener('mouseup',()=>drag=false);addEventListener('mousemove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.0023;pitch-=(e.clientY-ly)*.0018;pitch=Math.max(-1.2,Math.min(1.2,pitch));lx=e.clientX;ly=e.clientY})}
function animate(){requestAnimationFrame(animate);let dt=Math.min(T.getDelta(),.05),sp=22*dt,f=0,s=0;if(K.w||K.arrowup)f=1;if(K.s||K.arrowdown)f=-1;if(K.a||K.arrowleft)s=-1;if(K.d||K.arrowright)s=1;let d=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));C.position.addScaledVector(d,f*sp);C.position.addScaledVector(r,s*sp);C.position.x=Math.max(-22,Math.min(22,C.position.x));C.position.y=2.15;C.rotation.order='YXZ';C.rotation.y=yaw;C.rotation.x=pitch;if(rain){let p=rain.geometry.attributes.position.array;for(let i=1;i<p.length;i+=3){p[i]-=70*dt;if(p[i]<0){p[i]=110;p[i-1]=rand(-85,85)}}rain.geometry.attributes.position.needsUpdate=true}for(let c of cars){c.position.z+=c.userData.speed*dt;if(c.position.z>850)c.position.z=-850;if(c.position.z<-850)c.position.z=850}for(let i=0;i<signs.length;i++)signs[i].material.opacity=.72+.22*Math.sin(performance.now()*.002+i);R.render(S,C)}
addEventListener('resize',()=>{if(!C)return;C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight)});
document.getElementById('enter').onclick=()=>{document.getElementById('intro').style.opacity='0';document.getElementById('hud').style.opacity='1';document.getElementById('hint').style.opacity='1';setTimeout(()=>document.getElementById('intro').style.display='none',1200);try{let A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=52;g.gain.value=.012;o.connect(g);g.connect(a.destination);o.start()}catch(e){}};
world();
</script></body></html>''', height=900, scrolling=False)
